import React from "react";
import { Inter } from "next/font/google";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Home",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <style>{`.${inter.className} { /* your styles here */ }`}</style>
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
