import React from "react";
import { Inter } from "next/font/google";
import Head from "next/head"; // Import the Head component
import Header from "@/components/Header";
import "@/assets/css/style.scss";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Home",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        {children}
      </body>
    </html>
  );
}
