// components/AdminLayout.js
import React from "react";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });
export const metadata = {
  title: "Detail",
  description: "Generated by create next app",
};
export default function DetailLayout(props) {
  return <div>{props.children}</div>;
}
